const services = [
 ['01','WEBSITE DEVELOPMENT','Modern, responsive, and professional websites built for clear communication and growth.','◫'],['02','SYSTEMS DEVELOPMENT','Custom business systems designed to streamline operations and improve workflows.','⌘'],['03','AI SYSTEMS & AUTOMATION','Intelligent solutions that automate tasks and unlock practical possibilities.','✦'],['04','TRACKING SYSTEMS','Real-time tracking for vehicles, assets, people, and operations where required.','◎'],['05','MOBILE APPLICATIONS','Android and iOS applications tailored to your users and business needs.','▣'],['06','DESKTOP APPLICATIONS','Powerful desktop software for supported operating systems and business environments.','▤'],['07','E-COMMERCE SOLUTIONS','Online stores with product management, payment integration, and scalable functionality.','◈'],['08','DATABASE DESIGN & MANAGEMENT','Structured data systems designed to organize and manage business information.','⊞'],['09','DIGITAL MARKETING & BRANDING','Digital presence, brand identity, and marketing solutions tailored to client goals.','↗'],['10','CUSTOM SOLUTIONS & MORE','Have a unique idea? Let’s discuss a solution designed around your requirements.','+']
];
document.querySelector('#service-grid').innerHTML = services.map(([n,t,d,i])=>`<article class="service-card"><div><span class="service-no">${n}</span><span class="service-icon">${i}</span></div><h3>${t}</h3><p>${d}</p><a href="#contact">Explore service <b>→</b></a></article>`).join('');
const tech = [['Web Development','Clear, fast digital experiences shaped around your brand, audience, and business goals.'],['AI & Automation','Practical automation that reduces repetitive work and creates clearer paths through complex tasks.'],['Business Systems','Purpose-built systems that bring your workflows, information, and team operations together.'],['Tracking','Connected visibility for movements, assets, activity, and operations when the use case calls for it.'],['Mobile Apps','Useful native and cross-platform mobile experiences made around how people actually work.'],['Data & Infrastructure','Structured data and reliable foundations that help a digital product evolve over time.']];
const mods=document.querySelector('#tech-modules');
mods.innerHTML=tech.map(([t],i)=>`<button class="tech-module ${i===0?'active':''}" style="--i:${i}" data-index="${i}"><span>0${i+1}</span>${t}</button>`).join('');
function setTech(i){document.querySelectorAll('.tech-module').forEach((el,j)=>el.classList.toggle('active',j===i));document.querySelector('#tech-index').textContent=`0${i+1}`;document.querySelector('#tech-title').textContent=tech[i][0];document.querySelector('#tech-description').textContent=tech[i][1]}
mods.addEventListener('click',e=>{const b=e.target.closest('button');if(b)setTech(+b.dataset.index)});
const solutions = [['BUSINESS AUTOMATION','Repetitive tasks and disconnected steps can slow down everyday work.','We can map key processes and explore systems or automations that bring work into a clearer flow.','Teams handling repeatable operational tasks.'],['DIGITAL PRESENCE','A business needs a credible place to show its value and make an impression.','We can shape a website and digital presence around the people you need to reach.','Growing businesses, professionals, and organizations.'],['OPERATIONAL SYSTEMS','Information often sits across tools, documents, and informal processes.','We can design a central system around the workflow and information your team needs.','Businesses with evolving internal operations.'],['AI-POWERED WORKFLOWS','New AI capabilities should serve a useful, specific purpose.','We can identify suitable tasks and prototype practical AI-supported workflow improvements.','Teams exploring responsible AI adoption.'],['CUSTOM SOFTWARE','Some challenges need more than an off-the-shelf tool can provide.','We can explore an application designed around the operations and experience you need.','Businesses with specialised requirements.']];
document.querySelector('#solution-list').innerHTML=solutions.map(([t,p,a,b],i)=>`<article class="solution"><button aria-expanded="false"><span>0${i+1}</span><h3>${t}</h3><i>+</i></button><div class="solution-body"><div><small>THE CHALLENGE</small><p>${p}</p></div><div><small>POSSIBLE APPROACH</small><p>${a}</p></div><div><small>SUITABLE FOR</small><p>${b}</p></div><a href="#contact">Discuss requirements →</a></div></article>`).join('');
document.querySelector('#solution-list').addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const a=b.parentElement;document.querySelectorAll('.solution').forEach(x=>{if(x!==a)x.classList.remove('open')});a.classList.toggle('open');b.setAttribute('aria-expanded',a.classList.contains('open'))});
const nav=document.querySelector('.nav');addEventListener('scroll',()=>nav.classList.toggle('scrolled',scrollY>30));
document.querySelector('.menu-toggle').addEventListener('click',e=>{nav.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',nav.classList.contains('open'))});
document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
document.querySelector('#year').textContent=new Date().getFullYear();
document.querySelector('#contact-form').addEventListener('submit',e=>{e.preventDefault();e.target.querySelector('.form-status').textContent='Thank you — your project enquiry is ready to send. Connect this form to your preferred email or CRM service to receive it.';e.target.reset()});
const core=document.querySelector('.core-stage');if(!matchMedia('(prefers-reduced-motion: reduce)').matches)core.addEventListener('pointermove',e=>{const r=core.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;core.style.setProperty('--mx',`${x*10}deg`);core.style.setProperty('--my',`${-y*10}deg`)});
